import Link from "next/link";
import { Download, FileText, Printer } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PeriodFilter } from "@/components/period-filter";
import { ReportTree } from "@/components/report-tree";
import { getReports } from "@/lib/report-data";
import { money } from "@/lib/money";

export default async function BalanceSheetPage({ searchParams }: { searchParams: Promise<{ period?: string | string[] }> }) {
  const params = await searchParams;
  const selectedPeriod = typeof params.period === "string" ? params.period : undefined;
  const { balanceTree, balance, periodId, periods, periodLabel } = await getReports(selectedPeriod);
  const groups = balanceTree.filter((node) => ["ASSET", "LIABILITY", "EQUITY"].includes(node.accountType));
  const pdfHref = periodId ? `/api/reports/balance-sheet/pdf?period=${encodeURIComponent(periodId)}` : "/api/reports/balance-sheet/pdf";
  return <AppShell title="Neraca"><div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="label text-[#111111]">Laporan keuangan</div><h2 className="mt-2 text-3xl font-bold tracking-tight">Neraca</h2><p className="mt-2 text-sm text-[#6b7785]">Posisi aset, liabilitas, dan ekuitas pada periode terpilih.</p></div><div className="flex flex-wrap items-center gap-3"><PeriodFilter selected={periodId} periods={periods} /><Link href={pdfHref} aria-label="Unduh laporan Neraca PDF" className="flex h-10 items-center gap-2 whitespace-nowrap rounded-md bg-[#111111] px-3 text-sm font-semibold text-white"><FileText size={15} />PDF</Link><Link href="/api/reports/balance-sheet/excel" aria-label="Unduh laporan Neraca Excel" className="flex h-10 items-center gap-2 whitespace-nowrap rounded-md border border-[#dce2e7] bg-white px-3 text-sm font-semibold text-[#52606d]"><Download size={15} />Excel</Link><button className="flex h-10 items-center gap-2 whitespace-nowrap rounded-md border border-[#dce2e7] bg-white px-3 text-sm font-semibold text-[#52606d]"><Printer size={15} />Cetak</button></div></div><div className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e5e9ed] bg-[#fbfcfd] px-6 py-5"><div><div className="label">Periode laporan</div><div className="mt-1 font-semibold">{periodLabel}</div></div><div className={`rounded-full px-3 py-1 text-xs font-bold ${balance.balanced ? "bg-[#f0f0f0] text-[#2b2b2b]" : "bg-[#fff0ef] text-[#b13f37]"}`}>{balance.balanced ? "SEIMBANG" : "TIDAK SEIMBANG"}</div></div><div className="p-6"><div className="mb-2 grid grid-cols-[1fr_auto] border-b-2 border-[#18222c] pb-3 text-xs font-bold uppercase tracking-wider text-[#6b7785]"><span>Nama akun</span><span>Saldo</span></div><ReportTree nodes={groups} /></div><div className="grid gap-4 border-t border-[#e5e9ed] bg-[#fbfcfd] p-6 sm:grid-cols-3"><div><div className="label">Total aset</div><div className="money mt-1 text-lg font-bold">{money(balance.asset)}</div></div><div><div className="label">Liabilitas + ekuitas</div><div className="money mt-1 text-lg font-bold">{money(balance.liabilityAndEquity)}</div></div><div><div className="label">Selisih</div><div className="money mt-1 text-lg font-bold text-[#2b2b2b]">{money(balance.difference)}</div></div></div></div></div></AppShell>;
}
