import { Building2, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ConfirmForm } from "@/components/confirm-dialog";
import { createOrganizationAction } from "@/app/(app)/organizations/actions";
import { listOrganizations } from "@/server/services/organization.service";
import { requireSuperadmin } from "@/server/services/auth.service";

export default async function OrganizationsPage() {
  await requireSuperadmin();
  const organizations = await listOrganizations();
  return <AppShell title="Organisasi"><div className="space-y-7"><div><div className="label">Superadmin</div><h2 className="mt-2 text-3xl font-bold tracking-tight">Organisasi</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">Pisahkan transaksi antar cabang. Laporan konsolidasi tersedia di menu khusus.</p></div><ConfirmForm action={createOrganizationAction} message="Organisasi baru akan dibuat dengan daftar akun dan periode dari organisasi utama." className="panel grid gap-4 p-6 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="label">Nama organisasi<input name="name" required maxLength={150} className="mt-2 h-10 w-full rounded-md border border-[var(--border)] px-3 text-sm" placeholder="Contoh: Cabang Sparepart" /></label><label className="label">Slug opsional<input name="slug" maxLength={80} className="mt-2 h-10 w-full rounded-md border border-[var(--border)] px-3 text-sm" placeholder="cabang-sparepart" /></label><button className="h-10 rounded-md bg-[var(--primary)] px-4 text-sm font-bold text-white">Tambah organisasi</button></ConfirmForm><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{organizations.map((organization) => <div className="panel p-5" key={organization.id}><div className="flex items-start justify-between gap-4"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[var(--muted)]"><Building2 size={18} /></div><span className="rounded-full bg-[var(--muted)] px-2.5 py-1 text-[11px] font-bold">AKTIF</span></div><h3 className="mt-5 text-lg font-bold">{organization.name}</h3><p className="mt-1 text-xs text-[var(--muted-foreground)]">/{organization.slug}</p><div className="mt-5 grid grid-cols-3 gap-3 border-t border-[var(--border)] pt-4 text-xs"><div><div className="text-[var(--muted-foreground)]">Pengguna</div><div className="mt-1 flex items-center gap-1 font-bold"><Users size={13} />{organization._count.users}</div></div><div><div className="text-[var(--muted-foreground)]">Akun</div><div className="mt-1 font-bold">{organization._count.coaAccounts}</div></div><div><div className="text-[var(--muted-foreground)]">Jurnal</div><div className="mt-1 font-bold">{organization._count.journalTransactions}</div></div></div></div>)}</div></div></AppShell>;
}
