import { LockKeyhole, Plus, Trash2, UnlockKeyhole } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { demoPeriods } from "@/lib/demo-data";
import { listPeriods } from "@/server/services/accounting-period.service";
import { closePeriodAction, createPeriodAction, deletePeriodAction } from "@/app/(app)/periods/actions";

const periodLabel = (month: number, year: number) => `${new Date(year, month - 1, 1).toLocaleString("id-ID", { month: "long" })} ${year}`;

export default async function PeriodsPage() {
  const live = await listPeriods().catch(() => null);
  const periods = live ?? demoPeriods.map((period) => ({ ...period, startDate: new Date(), endDate: new Date(), createdAt: new Date(), updatedAt: new Date() }));
  const isDemo = !live;
  return <AppShell title="Periode"><div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="label text-[#138b82]">Kontrol periode</div><h2 className="mt-2 text-3xl font-bold tracking-tight">Periode akuntansi</h2><p className="mt-2 text-sm text-[#6b7785]">Pilih bulan laporan. Periode tertutup tidak bisa diubah.</p></div>{isDemo ? <span className="rounded-md border border-[#f0d4ad] bg-[#fff8ed] px-3 py-2 text-xs font-semibold text-[#a7651d]">Mode demo · database belum tersambung</span> : <span className="rounded-md bg-[#e5f3f1] px-3 py-2 text-xs font-semibold text-[#08776e]">Database tersambung</span>}</div>{!isDemo && <form action={createPeriodAction} className="panel flex flex-wrap items-end gap-3 p-5"><label className="label">Bulan<select name="month" className="mt-2 h-10 rounded-md border border-[#dce2e7] bg-white px-3 text-sm">{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2025, index, 1).toLocaleString("id-ID", { month: "long" })}</option>)}</select></label><label className="label">Tahun<input name="year" type="number" min="2000" max="9999" defaultValue={new Date().getFullYear()} className="mt-2 h-10 w-28 rounded-md border border-[#dce2e7] px-3 text-sm" /></label><button className="flex h-10 items-center gap-2 rounded-md bg-[#138b82] px-4 text-sm font-bold text-white"><Plus size={16} />Simpan periode</button></form>}<div className="grid max-w-4xl gap-4 sm:grid-cols-2 lg:grid-cols-3">{periods.map((period) => { const open = period.status === "OPEN"; return <div className="panel p-5" key={period.id}><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-lg ${open ? "bg-[#e5f3f1] text-[#08776e]" : "bg-[#edf0f2] text-[#5f6d7a]"}`}>{open ? <UnlockKeyhole size={19} /> : <LockKeyhole size={19} />}</div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${open ? "bg-[#e5f3f1] text-[#08776e]" : "bg-[#edf0f2] text-[#5f6d7a]"}`}>{open ? "TERBUKA" : "TERTUTUP"}</span></div><div className="mt-5 text-lg font-bold">{periodLabel(period.month, period.year)}</div><div className="mt-1 text-sm text-[#8a96a3]">{open ? "Bisa menerima input saldo" : "Input dikunci untuk menjaga riwayat"}</div>{!isDemo && <div className="mt-5 flex gap-2 border-t border-[#eef1f3] pt-4">{open && <form action={closePeriodAction}><input type="hidden" name="id" value={period.id} /><button className="flex items-center gap-1.5 rounded-md bg-[#edf0f2] px-2.5 py-1.5 text-xs font-semibold text-[#52606d]"><LockKeyhole size={14} />Tutup</button></form>}<form action={deletePeriodAction}><input type="hidden" name="id" value={period.id} /><button className="rounded-md p-1.5 text-[#b13f37] hover:bg-[#fff0ef]" title="Hapus periode"><Trash2 size={15} /></button></form></div>}</div>; })}</div></div></AppShell>;
}
