import { AppShell } from "@/components/app-shell";
import { PeriodFilter } from "@/components/period-filter";
import { ReportTree } from "@/components/report-tree";
import { getConsolidatedReports } from "@/lib/report-data";
import { money } from "@/lib/money";

export default async function ConsolidatedReportPage({ searchParams }: { searchParams: Promise<{ period?: string | string[] }> }) {
  const params = await searchParams;
  const selectedPeriod = typeof params.period === "string" ? params.period : undefined;
  const { balanceTree, balance, profitLossTree, profitLoss, periodId, periods, periodLabel, organizations } = await getConsolidatedReports(selectedPeriod);
  return <AppShell title="Konsolidasi"><div className="space-y-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="label">Superadmin · laporan gabungan</div><h2 className="mt-2 text-3xl font-bold tracking-tight">Laporan konsolidasi</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">Gabungan laporan semua organisasi tanpa mencampur penyimpanan transaksi operasional.</p></div><PeriodFilter selected={periodId} periods={periods} /></div><div className="flex flex-wrap gap-2">{organizations.map((organization) => <span className="rounded-full bg-[var(--muted)] px-3 py-1.5 text-xs font-semibold" key={organization.id}>{organization.name}</span>)}</div><div className="grid gap-5 xl:grid-cols-2"><section className="panel overflow-hidden"><div className="border-b border-[var(--border)] px-6 py-5"><div className="label">Neraca gabungan</div><div className="mt-1 font-semibold">{periodLabel}</div></div><div className="p-6"><ReportTree nodes={balanceTree.filter((node) => ["ASSET", "LIABILITY", "EQUITY"].includes(node.accountType))} /><div className="mt-6 grid gap-3 border-t border-[var(--border)] pt-5 text-sm"><div className="flex justify-between"><span className="text-[var(--muted-foreground)]">Total aset</span><strong className="money">{money(balance.asset)}</strong></div><div className="flex justify-between"><span className="text-[var(--muted-foreground)]">Liabilitas + ekuitas</span><strong className="money">{money(balance.liabilityAndEquity)}</strong></div></div></div></section><section className="panel overflow-hidden"><div className="border-b border-[var(--border)] px-6 py-5"><div className="label">Laba rugi gabungan</div><div className="mt-1 font-semibold">{periodLabel}</div></div><div className="p-6"><ReportTree nodes={profitLossTree} /><div className="mt-6 space-y-3 border-t border-[var(--border)] pt-5 text-sm"><div className="flex justify-between"><span className="text-[var(--muted-foreground)]">Total pendapatan</span><strong className="money">{money(profitLoss.revenue)}</strong></div><div className="flex justify-between"><span className="text-[var(--muted-foreground)]">Total beban</span><strong className="money">{money(profitLoss.expense)}</strong></div><div className="flex justify-between rounded-md bg-[var(--muted)] px-4 py-3 font-bold"><span>Laba / rugi bersih</span><strong className="money">{money(profitLoss.netProfitLoss)}</strong></div></div></div></section></div></div></AppShell>;
}
