"use client";

import { Pencil, X } from "lucide-react";
import { useState } from "react";
import { updateUserAccessAction, updateUserPasswordAction } from "@/app/(app)/users/actions";

type User = { id: string; name: string; email: string; role: string; canViewConsolidated: boolean; organizationAccesses: { organizationId: string; organization: { id: string; name: string } }[] };
type Organization = { id: string; name: string };

export function UserEditDialog({ user, organizations, canManageAccess }: { user: User; organizations: Organization[]; canManageAccess: boolean }) {
  const [open, setOpen] = useState(false);
  return <>
    <button type="button" onClick={() => setOpen(true)} className="flex h-8 items-center gap-1.5 rounded-md bg-[var(--muted)] px-3 text-xs font-bold text-[var(--foreground)]"><Pencil size={13} />Edit</button>
    {open && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section role="dialog" aria-modal="true" aria-labelledby={`edit-user-${user.id}`} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl border border-[var(--border)] bg-[var(--card)] p-6 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="label">Pengaturan pengguna</div><h2 id={`edit-user-${user.id}`} className="mt-2 text-xl font-bold">{user.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{user.email}</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-md p-2 text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Tutup modal"><X size={18} /></button></div><form action={updateUserPasswordAction} onSubmit={() => setOpen(false)} className="mt-6 space-y-3 border-t border-[var(--border)] pt-5"><input type="hidden" name="id" value={user.id} /><h3 className="text-sm font-bold">Kata sandi</h3><div className="flex gap-2"><input name="password" type="password" minLength={8} required placeholder="Minimal 8 karakter" className="h-10 min-w-0 flex-1 rounded-md border border-[var(--border)] px-3 text-sm" /><button className="h-10 rounded-md bg-[var(--primary)] px-3 text-xs font-bold text-white">Simpan</button></div></form>{canManageAccess && <form action={updateUserAccessAction} onSubmit={() => setOpen(false)} className="mt-6 space-y-3 border-t border-[var(--border)] pt-5"><input type="hidden" name="userId" value={user.id} /><h3 className="text-sm font-bold">Akses organisasi</h3><div className="space-y-2">{organizations.map((organization) => <label key={organization.id} className="flex min-h-9 items-center gap-2 text-sm"><input type="checkbox" name="organizationId" value={organization.id} defaultChecked={user.organizationAccesses.some((access) => access.organizationId === organization.id)} className="h-4 w-4 accent-[var(--foreground)]" />{organization.name}</label>)}</div><label className="flex min-h-9 items-center gap-2 border-t border-[var(--border)] pt-3 text-sm"><input type="checkbox" name="canViewConsolidated" value="true" defaultChecked={user.canViewConsolidated} className="h-4 w-4 accent-[var(--foreground)]" />Boleh melihat laporan konsolidasi</label><button className="h-10 rounded-md bg-[var(--primary)] px-4 text-xs font-bold text-white">Simpan akses</button></form>}</section></div>}
  </>;
}
