import { AppShell } from "@/components/app-shell";
import { JournalImport } from "@/components/journal-import";
import { money } from "@/lib/money";
import { listJournalTransactions } from "@/server/services/journal.service";

const dateLabel = (date: Date) => new Date(date).toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" });
const periodLabel = (month: number, year: number) => `${new Date(year, month - 1, 1).toLocaleString("id-ID", { month: "long" })} ${year}`;

export default async function JournalPage() {
  const transactions = await listJournalTransactions().catch(() => []);
  return <AppShell title="Jurnal Umum"><div className="space-y-6"><div><div className="label text-[#138b82]">Transaksi keuangan</div><h2 className="mt-2 text-3xl font-bold tracking-tight">Jurnal umum</h2><p className="mt-2 text-sm text-[#6b7785]">Import transaksi dari file Excel client dan pantau data yang sudah masuk.</p></div><div className="grid gap-5 xl:grid-cols-[minmax(320px,.75fr)_minmax(0,1.25fr)]"><JournalImport /><section className="panel overflow-hidden"><div className="border-b border-[#e5e9ed] p-6"><h3 className="font-bold">Transaksi terakhir</h3><p className="mt-1 text-sm text-[#6b7785]">Menampilkan maksimal 100 transaksi terbaru.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fbfcfd] text-xs uppercase tracking-wider text-[#7e8b97]"><tr><th className="px-5 py-4">Tanggal</th><th className="px-5 py-4">Akun</th><th className="px-5 py-4">Deskripsi</th><th className="px-5 py-4 text-right">Debet</th><th className="px-5 py-4 text-right">Kredit</th></tr></thead><tbody className="divide-y divide-[#eef1f3]">{transactions.length ? transactions.map((transaction) => <tr key={transaction.id}><td className="whitespace-nowrap px-5 py-4 text-[#6b7785]">{dateLabel(transaction.transactionDate)}</td><td className="px-5 py-4"><div className="font-mono text-xs text-[#8a96a3]">{transaction.coaAccount.code}</div><div className="mt-1 font-semibold">{transaction.coaAccount.name}</div><div className="mt-1 text-xs text-[#8a96a3]">{periodLabel(transaction.accountingPeriod.month, transaction.accountingPeriod.year)}</div></td><td className="max-w-[260px] truncate px-5 py-4 text-[#6b7785]">{transaction.description || "-"}</td><td className="money whitespace-nowrap px-5 py-4 text-right">{transaction.debit.gt(0) ? money(transaction.debit) : "-"}</td><td className="money whitespace-nowrap px-5 py-4 text-right">{transaction.credit.gt(0) ? money(transaction.credit) : "-"}</td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-[#8a96a3]">Belum ada transaksi jurnal.</td></tr>}</tbody></table></div></section></div></div></AppShell>;
}
